config/routes.rb
Saad::Application.routes.draw do

  resources :schedules

  resources :sections

  resources :departments

  resources :timeslots

  resources :section_subjects

  resources :day_timeslots

  resources :professors

  resources :rooms

  resources :subjects

  resources :days

  resources :users

get 'admin' => 'admin#index'

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

get "website/index"

  controller :pages do
    get 'about' => :about
    get 'contact' => :contact
    get 'new_user' => :new_user
    get 'database' => :database
    get 'system' => :system
  end

  root :to => 'website#index', :as => 'website'

  

end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :day_timeslots

	validates :name, :desc, :presence => true
end

app/models/day_timeslot.rb
class DayTimeslot < ActiveRecord::Base
  belongs_to :day
  belongs_to :timeslot

  has_many :schedules

	validates :day_id, :timeslot_id, :presence => true

def jcon
  	[day.name, timeslot.timecon].join(' ')
  end
  
end

app/models/department.rb
class Department < ActiveRecord::Base

	has_many :sections

	validates :name, :desc, :presence => true

end

app/models/professor.rb
class Professor < ActiveRecord::Base

	def procon
		[lastname, firstname, middleinitial].join(', ')
	end

	validates  :lastname, :firstname, :middleinitial, :status, :presence => true
end

app/models/room.rb
class Room < ActiveRecord::Base

	validates :name, :desc, :presence => true
	
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :day_timeslot
  belongs_to :section_subject
  belongs_to :professor
  belongs_to :room

  default_scope :order => 'day_timeslot_id'

  validates :day_timeslot_id, :section_subject_id, :professor_id, :room_id, :presence => true

  validates :section_subject_id, :uniqueness => true

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :department

  has_many :section_subjects

  def seccon
  	[name, department.name, yearlevel].join
  end

  validates :name, :department_id, :yearlevel, :presence => true

end

app/models/section_subject.rb
class SectionSubject < ActiveRecord::Base
  belongs_to :section
  belongs_to :subject

  has_many :schedules

  def jcon
  	[subject.name, section.seccon].join
  end

  validates :section_id, :subject_id, :presence => true

end

app/models/subject.rb
class Subject < ActiveRecord::Base

	has_many :section_subjects

validates :name, :desc, :load, :presence => true

end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base

	has_many :day_timeslots

	def timecon
  		[start.to_s(:time), finish.to_s(:time)].join(' - ')
	end

validates :start, :finish, :presence => true

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true

	validates :password, :confirmation => true
	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(name, password)
		if user = find_by_name(name)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password

		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	private

	def password_must_be_present
			errors.add(:password, "Missing password") unless hashed_password.present?
	end

	

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end

	





end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:name, :desc)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :desc, :load)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :load %><br>
    <%= f.number_field :load %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Load</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.desc %></td>
        <td><%= subject.load %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @subject.desc %>
</p>

<p>
  <strong>Load:</strong>
  <%= @subject.load %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>