config/routes.rb
Saad::Application.routes.draw do

  resources :schedules

  resources :sections

  resources :departments

  resources :timeslots

  resources :section_subjects

  resources :day_timeslots

  resources :professors

  resources :rooms

  resources :subjects

  resources :days

  resources :users

get 'admin' => 'admin#index'

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

get "website/index"

  controller :pages do
    get 'about' => :about
    get 'contact' => :contact
    get 'new_user' => :new_user
    get 'database' => :database
    get 'system' => :system
  end

  root :to => 'website#index', :as => 'website'

  

end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :day_timeslots

	validates :name, :desc, :presence => true
end

app/models/day_timeslot.rb
class DayTimeslot < ActiveRecord::Base
  belongs_to :day
  belongs_to :timeslot

  has_many :schedules

	validates :day_id, :timeslot_id, :presence => true

def jcon
  	[day.name, timeslot.timecon].join(' ')
  end
  
end

app/models/department.rb
class Department < ActiveRecord::Base

	has_many :sections

	validates :name, :desc, :presence => true

end

app/models/professor.rb
class Professor < ActiveRecord::Base

	def procon
		[lastname, firstname, middleinitial].join(', ')
	end

	validates  :lastname, :firstname, :middleinitial, :status, :presence => true
end

app/models/room.rb
class Room < ActiveRecord::Base

	validates :name, :desc, :presence => true
	
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :day_timeslot
  belongs_to :section_subject
  belongs_to :professor
  belongs_to :room

  default_scope :order => 'day_timeslot_id'

  validates :day_timeslot_id, :section_subject_id, :professor_id, :room_id, :presence => true

  validates :section_subject_id, :uniqueness => true

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :department

  has_many :section_subjects

  def seccon
  	[name, department.name, yearlevel].join
  end

  validates :name, :department_id, :yearlevel, :presence => true

end

app/models/section_subject.rb
class SectionSubject < ActiveRecord::Base
  belongs_to :section
  belongs_to :subject

  has_many :schedules

  def jcon
  	[subject.name, section.seccon].join
  end

  validates :section_id, :subject_id, :presence => true

end

app/models/subject.rb
class Subject < ActiveRecord::Base

	has_many :section_subjects

validates :name, :desc, :load, :presence => true

end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base

	has_many :day_timeslots

	def timecon
  		[start.to_s(:time), finish.to_s(:time)].join(' - ')
	end

validates :start, :finish, :presence => true

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true

	validates :password, :confirmation => true
	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(name, password)
		if user = find_by_name(name)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password

		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end
	end

	private

	def password_must_be_present
			errors.add(:password, "Missing password") unless hashed_password.present?
	end

	

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end

	





end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:name, :desc)
    end
end

app/controllers/section_subjects_controller.rb
class SectionSubjectsController < ApplicationController
  before_action :set_section_subject, only: [:show, :edit, :update, :destroy]

  # GET /section_subjects
  # GET /section_subjects.json
  def index
    @section_subjects = SectionSubject.all
  end

  # GET /section_subjects/1
  # GET /section_subjects/1.json
  def show
  end

  # GET /section_subjects/new
  def new
    @section_subject = SectionSubject.new
  end

  # GET /section_subjects/1/edit
  def edit
  end

  # POST /section_subjects
  # POST /section_subjects.json
  def create
    @section_subject = SectionSubject.new(section_subject_params)

    respond_to do |format|
      if @section_subject.save
        format.html { redirect_to @section_subject, notice: 'Section subject was successfully created.' }
        format.json { render action: 'show', status: :created, location: @section_subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @section_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /section_subjects/1
  # PATCH/PUT /section_subjects/1.json
  def update
    respond_to do |format|
      if @section_subject.update(section_subject_params)
        format.html { redirect_to @section_subject, notice: 'Section subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @section_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_subjects/1
  # DELETE /section_subjects/1.json
  def destroy
    @section_subject.destroy
    respond_to do |format|
      format.html { redirect_to section_subjects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section_subject
      @section_subject = SectionSubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_subject_params
      params.require(:section_subject).permit(:section_id, :subject_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/section_subjects_helper.rb
module SectionSubjectsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/section_subjects/_form.html.erb
<%= simple_form_for(@section_subject) do |f| %>
  <% if @section_subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section_subject.errors.count, "error") %> prohibited this section_subject from being saved:</h2>

      <ul>
      <% @section_subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :section do %>
      <%= f.select :section_id, Section.all.map{|s| [s.seccon, s.id]}, :include_blank => true %>
    <% end %>
  
    <%= f.association :subject %>
  
    <%= f.button :submit %>
  
<% end %>

app/views/section_subjects/edit.html.erb
<h1>Editing section_subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @section_subject %> |
<%= link_to 'Back', section_subjects_path %>

app/views/section_subjects/index.html.erb
<h1>Listing section_subjects</h1>

<table>
  <thead>
    <tr>
      <th>Section</th>
      <th>Subject</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @section_subjects.each do |section_subject| %>
      <tr>
        <td><%= section_subject.subject.name %></td>
        <td><%= section_subject.section.seccon %></td>
        
        <td><%= link_to 'Show', section_subject %></td>
        <td><%= link_to 'Edit', edit_section_subject_path(section_subject) %></td>
        <td><%= link_to 'Destroy', section_subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section subject', new_section_subject_path %>

app/views/section_subjects/new.html.erb
<h1>New section_subject</h1>

<%= render 'form' %>

<%= link_to 'Back', section_subjects_path %>

app/views/section_subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Section:</strong>
  <%= @section_subject.section %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @section_subject.subject %>
</p>

<%= link_to 'Edit', edit_section_subject_path(@section_subject) %> |
<%= link_to 'Back', section_subjects_path %>